### ISSUE TITLE
default version gives 404 error on aarch64 + linux

### ISSUE THREAD

**Issue by skennedy** [coursier/setup-action#709]
Looks like the [v1.3.8](https://github.com/coursier/setup-action/compare/v1.3.7...v1.3.8) version of the action changed a few defaults
1. the default coursier version is 2.1.17
2. on aarch64 it downloads from https://github.com/coursier/coursier/ instead of https://github.com/VirtusLab/coursier-m1/

This has broken aarch64 on linux as there are no builds for that in https://github.com/coursier/coursier/ but there were at https://github.com/VirtusLab/coursier-m1/

**Comment by tgodzik** [comment]
Fixed in https://github.com/coursier/setup-action/pull/718/files

**Comment by vlovgr** [comment]
@alexarchambault @tgodzik Thanks for the fix! Would it be possible to get a new release out? When using `coursier/setup-action@v1`, this is still an issue.

**Comment by alexarchambault** [comment]
@vlovgr Should be fixed with [`1.3.9`](https://github.com/coursier/setup-action/releases/tag/v1.3.9) (`v1.3` and `v1` tags updated as well)

**Comment by vlovgr** [comment]
Thanks @alexarchambault, much appreciated.
